vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        post_thumbnail:
            uri_prefix: /public/uploads/media
            upload_destination: '%kernel.project_dir%/public/uploads/media'
            # Will rename uploaded files using a uniqueid as a prefix.
            namer: Vich\UploaderBundle\Naming\OrignameNamer