api_platform:
  resources:
  App\Entity\Product:
    collectionOperations:
      search:
        method: "GET"
        path: "/products/search"
        controller: 'App\Controller\ProductSearchController::search'
        defaults:
          _api_resource_class: 'App\Entity\Product'
          _api_collection_operation_name: "search"
  type: api_platform
  prefix: /api
